version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "4000:80"
    depends_on:
      - app
